### ISSUE TITLE
权限管理问题

### ISSUE THREAD

**Issue by wangsui1314** [ueboot/ueboot-starter#1]
在创建其他用户的情况下，若针对菜单中，不勾选权限管理，则其他用户登录不上

**Comment by yaakua** [comment]
不勾选权限管理菜单，不影响用户登录。给出具体的操作界面看看

**Comment by yaakua** [comment]
默认登录后会跳转到系统管理的用户列表页面，如果当前用户没有这个菜单权限则会提示没有权限。
可以将登录成功后的跳转地址修改为其他可以访问的页面，比如：/ 如下图：
![image](https://user-images.githubusercontent.com/1543846/55712428-4e902180-5a21-11e9-9c03-e9ef5b0dc813.png)
