### ISSUE TITLE
maven 没有拉取到包

### ISSUE THREAD

**Issue by guomingcheng** [ueboot/ueboot-starter#2]
请问，我把项目导入 idea，但是 maven 没有拉取到相关依赖的  jar。我上一次出现这个问题是，项目依赖的 jar 包在私服中，mavne 的配置文件没有指向私服，修改后就可以下载依赖。不知这个后台项目是否也是这样，如果不是那我该如何解决呢。

**Comment by 151608133** [comment]
修改maven 远程仓库地址，仔细看开始文档有说明 。
